import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// import Header from "@/app//components/Header";
// import Footer from "@/app//components/Footer";
import { Header, Footer } from "@/app/components";
import LoadingBar from "./components/LoadingBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "La Blog | Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={`${inter.className} bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-sky-400 to-sky-100`}
      >
        <Providers>
          <Header />
          <LoadingBar />
          <main
            className="flex m-auto xl:container min-h-screen 
                flex-col items-center justify-between p-3 lg:p-5"
          >
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
