import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Header, Footer } from "@/app/components";
import LoadingBar from "./components/LoadingBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "La Blog | Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body
        className={`${inter.className} 
      bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-sky-400 to-sky-100
      dark:bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] dark:from-gray-900 dark:to-gray-600 dark:bg-gradient-to-t
      `}
      >
        <Providers>
          <Header />
          <LoadingBar />
          <main className=" m-auto p-3 lg:p-5 xl:p-10 xl:container min-h-screen flex flex-col items-center justify-between">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
